done with script

diff --git a/helloGameHub b/helloGameHub
--- a/helloGameHub
+++ b/helloGameHub
@@ -8,6 +8,7 @@ NWJS_DL_BASE_URL=http://dl.nwjs.io/v0.11.6
 NWJS_DL_URL=$NWJS_DL_BASE_URL/$NWJS_LINUX_FILENAME
 NWJS_PACKAGE_FILE=$NWJS_LINUX_FILENAME
 NWJS_LOC=$NWJS_LINUX
+APP_NAME=app.nw
 
 #download function
 function download_package {
@@ -21,6 +22,7 @@ function download_package {
 }
 
 function extract_package {
+    echo "Extracting NW.js"
     if [ "$(uname -s)" != 'Linux' ]; then
         unzip dl/$NWJS_MAC_FILENAME
     else
@@ -41,11 +43,17 @@ if [ ! -d $NWJS_LOC ]; then
     extract_package
 fi
 
+#Create app
+zip app.nw index.html package.json
 
-#Uncompress package
-if [ ! -d $NWJS_LINUX -a ! -d $NWJS_MAC ]; then
-    echo "not dir"
+#Run App
+$NWJS_LOC/nw $APP_NAME
+if [ $? -eq 0 ]; then
+    echo "OK"
 else
-    echo "is dir"
+    echo ""
+    echo "Si estas en ubuntu 14.04 x64 y te tiro un error de que no"
+    echo "puede cargar la libreria libudev.so.0 entonces corre:"
+    echo "sudo ln -sf /lib/x86_64-linux-gnu/libudev.so.1 /lib/x86_64-linux-gnu/libudev.so.0"
+    echo ""
 fi
-
